name: AdvancedChat
version: "2.5"
main: me.lovelace.advancedChat.AdvancedChat
api-version: '1.21.11'
softdepend: [PlaceholderAPI, CMI, ProtocolLib]
libraries:
  - "com.github.ben-manes.caffeine:caffeine:3.1.8"
commands:
  ach:
    description: Основная команда плагия
    aliases: [chat]
  channel:
    description: Переключить канал чата
    aliases: [ch, c]
  ignorechat:
    description: Игнорировать игрока
    aliases: [ignore]
  messagedelete:
    description: Удалить сообщение
    aliases: [md]
  messageedit:
    description: Редактировать сообщение
    aliases: [medit]
  silent:
    description: Включить/выключить тихий режим
  chatclear:
    description: Очистка чата
    aliases: [cc]
  tagtoggle:
    description: Включить/выключить упоминания себя
  spy:
    description: Режим шпиона
permissions:
  advancedchat.admin:
    default: op
  advancedchat.use:
    default: true
  advancedchat.delete.own:
    default: true
  advancedchat.delete:
    default: true
  advancedchat.delete.others:
    default: op
  advancedchat.delete.admin:
    default: op
  advancedchat.edit:
    default: true
  advancedchat.edit.others:
    default: op
  advancedchat.edit.admin:
    default: op
  advancedchat.mention:
    default: true
  advancedchat.mention.everyone:
    default: op
  advancedchat.mention.everyone.bypass:
    default: op
  advancedchat.links:
    default: true
  advancedchat.color:
    default: true
  advancedchat.silent:
    default: true
  advancedchat.tagtoggle:
    default: op
  advancedchat.spy:
    default: op
  advancedchat.clear.global:
    default: op
  advancedchat.clear.console:
    default: op
  chat.edit:
    description: "Разрешает удалять и редактировать свои сообщения"
    default: true
  chat.edit.admin:
    description: "Разрешает удалять и редактировать чужие сообщения"
    default: op
  # Reactions permissions
  advancedchat.reaction.use:
    default: true
  advancedchat.reaction.see:
    default: true
  advancedchat.reaction.admin:
    default: op
  # Quote/Reply permissions
  advancedchat.quote.use:
    default: true
  advancedchat.quote.see:
    default: true
